[workspace]
resolver = "2"
members = [
    "src/lib",
    "src/daemon",
]

[workspace.package]
version = "0.2.0"
edition = "2024"
rust-version = "1.96"
license = "Apache-2.0"
documentation = "https://github.com/cathay4t/shuli"
repository = "https://github.com/cathay4t/shuli"

[workspace.dependencies]
log = "0.4"
env_logger = "0.11"
serde = { version = "1", features = ["derive"] }
rmsd_yaml = "0.1"
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "signal", "sync", "time"] }
futures = "0.3"
netlink-packet-core = "0.9"
netlink-packet-generic = "0.5"
genetlink = "0.3"
netlink-proto = "0.13"
netlink-sys = "0.9"
rtnetlink = "0.23"
wl-nl80211 = { git = "https://github.com/rust-netlink/wl-nl80211.git" }
mozim = { version = "0.3.2", default-features = false, features = ["netlink"] }
p256 = { version = "0.14", features = ["arithmetic", "hash2curve", "ecdh", "getrandom"] }
getrandom = { version = "0.4", features = ["sys_rng"] }
aws-lc-rs = "1"
libc = "0.2"
nispor = "2"
rustls = { version = "0.23", default-features = false, features = ["ring", "logging", "std", "tls12"] }
